Navigation: View Experiences
alan-turing-institute/AutSPACEs pull request #147
Opened 2021-07-27 10:53 UTC by anoura12

2021-07-29 10:39 UTC, jhlink requested changes
Hey @anoura12 ! 

Strong work!

Unfortunately, when I ran your PR, I got this NoReverseMatch error. 

![CleanShot 2021-07-29 at 06 38 21@2x](https://user-images.githubusercontent.com/1872836/127477960-9a43960a-c4eb-48a9-aa6e-7e4e5bcfdef0.jpg)


It seems that all the references to `public_experiences` in the templates haven't been changed to `view_experiences`. Please re-request a review for me when this is finished and the docker instance doesn't show an error on start. :)

2021-07-29 13:21 UTC, anoura12 commented
@jhlink I have made the changes in all files. Could you take a look at them?

2021-08-03 10:56 UTC, anoura12 commented
@jhlink I think I've resolved the merge conflicts. Is it good to merge now?

2021-08-03 11:00 UTC, jhlink commented
@anoura12 I'll take a look later today!

2021-08-04 13:12 UTC, jhlink commented
PR is good. Merging.

2021-08-04 13:13 UTC, merged

2021-08-04 13:19 UTC, jhlink reviewed
@anoura12 , please create another PR with the changes I've specified here. 
Unfortunately, I had to revert the PR because you've overwritten Mridu's PR.

2021-08-04 13:29 UTC, anoura12 commented on server/apps/main/templates/main/moderate_public_experiences.html
> +             <a style="color:#000000;"href="#" class="active">About</a>
Yeah will do