Remind the user to complete their profile
alan-turing-institute/AutSPACEs pull request #578
Opened 2023-08-30 17:21 UTC by llewelld

If the user submits an experience with either the research or public flags set, but hasn't yet completed their user profile, this change will redirect the user to the profile page with a suitable message requesting that they complete it.

Fixes #534.

2023-08-30 17:23 UTC, llewelld commented
This will need to be rejigged slightly after #569 has been merged to move the updated profile messages into the new profile messages file.

2023-08-30 17:29 UTC, llewelld commented
Switching to draft while I update the unit tests.

2023-08-31 09:38 UTC, gedankenstuecke requested changes
Overall this works really great, well done @llewelld! I left some in-line comments for the tests, where the doc-strings & comments don't match what we test for right now. 

Otherwise there's a slightly larger question about the approach for how to send the "message" to the user when the redirect to the profile happens. Currently you've made a partial for the profile messages and embedded that directly in the `profile.html` where it will be shown when appropriate. 

What I had in mind was using the actual `messages` feature of Django instead: 

In our main `application.html` we already have defined a place where those messages can be shown as boxes, c.f. https://github.com/alan-turing-institute/AutSPACEs/blob/1405bf11afbf7470be457fc0a22811b1b348516a/server/apps/main/templates/main/application.html#L36 

Currently this is only used to raise errors up as messages when trying to submit an experience, c.f. https://github.com/alan-turing-institute/AutSPACEs/blob/1405bf11afbf7470be457fc0a22811b1b348516a/server/apps/main/views.py#L186

While we might want to change this to the Bootstrap validation also used for the forms eventually for consistency, I wonder if using the messages approach might be a good alternative to avoid repeating the message interface code and being able to define it only once? 

Having said all that, I don't have really strong opinions either way, and there might be good reasons to implement it using the partials that i've overlooked!

2023-08-31 09:38 UTC, gedankenstuecke commented on server/apps/main/tests/test_views.py
> +        assert len(pe_db_after) == 0
Maybe I'm having a brainfart, but shouldn't this be `len==1` if the story exists?

2023-08-31 09:38 UTC, gedankenstuecke commented on server/apps/main/tests/test_views.py
> +        assert user_a_stories_after == user_a_stories_before
Same here, doesn't this validate that we have 0 experiences after adding one?

2023-08-31 09:38 UTC, gedankenstuecke commented on server/apps/main/tests/test_views.py
> +        shared publicly and for research
Based on the function title (& logic below) I guess that this one actually tests that the redirect is to the confirmation page?

2023-08-31 09:38 UTC, gedankenstuecke commented on server/apps/main/tests/test_views.py
> +        assert len(pe_db_after) == 0
Nevermind, I guess I understood now, It's 0 for both as the experience is not public, it's just that the comments need to be adjusted to reflect what we actually test for :)

2023-09-12 15:05 UTC, llewelld commented
After user testing and discussion, we're going to add in a 'Success' page after the user submits a Story, so this nudging will have to be moved to this success page in this case. Consequently it doesn't make sense to keep this so I'm closing it.

2023-09-12 15:05 UTC, closed without merging