User Testing: Restore DB to initial conditions
alan-turing-institute/AutSPACEs pull request #585
Opened 2023-09-08 11:00 UTC by helendduncan

closes #584 
Management command to delete the user and their OH data and then remove the seeded stories from the DB
Edited `seed_db.py` to remove its analogous functions.

2023-09-08 15:50 UTC, gedankenstuecke requested changes
I think there's actually a way that's a lot easier to achieve the same thing. Which the original file in `seed_db` didn't take into account either, but I just noticed this:

`PublicExperience` objects use `on_delete=models.CASCADE`, so by iterating over all users and deleting them, the corresponding public experiences are deleted as well! 

Does that make sense?

2023-09-08 16:13 UTC, helendduncan commented
I like it - Frustratingly the test fails - I am assuming that there are multiple calls to an external function and the cassette only allows one - but I can't quite see how that would be the case as there should only be one deletion - the user's profile

2023-09-08 16:22 UTC, gedankenstuecke commented
yeah, it looks like only `oh_id=12345678` is the one that should be deleted, not the other one 🤔

2023-09-08 17:02 UTC, gedankenstuecke commented
@helendduncan I [found the problem in the docs of `django-open-humans`](https://django-open-humans.readthedocs.io/en/latest/modules/configuration.html#environment-variables)!

The default for `OPENHUMANS_DEAUTH_ON_DELETE` is `True`, which means that if we end up deleting a `User` object in our DB, we try to also ID the `OpenHumansMember` object associated and then send through a message through to Open Humans to please de-auth that user on their end as well. 

With our made-up user `999999999` that of course doesn't work, as the access_token is made-up. To fix this `OPENHUMANS_DEAUTH_ON_DELETE = False` needs to be added to the config that is used to run the test!

2023-09-08 17:04 UTC, gedankenstuecke commented
I'd actually suggest just adding that flag into the `development.py` setting as I think it's quite reasonable to have this disabled in both development & testing (and testing also uses those settings atm)

2023-09-11 11:18 UTC, gedankenstuecke approved these changes
That looks great, thanks @helendduncan! Also great that the tests now pass 🚀

2023-09-12 14:27 UTC, merged